version: "3"
services:
  nginx:
    image: giffits/fileservice-nginx
    container_name: nginx
    hostname: nginx
    build:
      context: ../
    ports:
    - 80:80
    networks:
    - frontend
    depends_on:
    - php
  php:
    image: giffits/fileservice-php
    container_name: php
    hostname: php
    build:
      context: ../
    networks:
    - frontend
  mariadb:
    image: giffits/fileservice-mariadb
    container_name: mariadb
    hostname: mariadb
    build:
      context: ../
      dockerfile: ./docker/containers/mariadb/Dockerfile
    ports:
    - 3306:3306
    networks:
    - frontend
  elasticsearch:
    image: giffits/fileservice-elasticsearch
    container_name: elasticsearch
    hostname: elasticseach
    build:
      context: ../
      dockerfile: ./docker/containers/elasticsearch/Dockerfile
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
    - 9200:9200
    networks:
    - frontend
networks:
  frontend:
    driver: bridge
