version: "3"
services:
  nginx:
    build:
      dockerfile: ./docker/containers/nginx/dev/Dockerfile
    volumes:
    - ../app:/var/www/app
  php:
    build:
      dockerfile: ./docker/containers/php/dev/Dockerfile
    environment:
      APP_ENV: "dev"
      APP_DEBUG: 1
    volumes:
    - ../api:/var/www/api
  mariadb:
    volumes:
    - ../data/mariadb:/var/lib/mysql
    - ../migrations/mariadb:/docker-entrypoint-initdb.d/
  elasticsearch:
    volumes:
#    - ../data/elasticsearch:/var/elasticsearch/data
    - ../data/elasticsearch:/usr/share/elasticsearch/data
